hassanhabib/EventHighway

EventHighway.Core/Models/EventCall/V2/EventCallV2.cs
EventHighway.sln

DATA: Add Event Call V2

---

EventHighway.Core/Brokers/Storages/StorageBroker.EventV2s.cs
EventHighway.Core/Migrations/20250303072037_Add&MigrateEventV2.Designer.cs
EventHighway.Core/Migrations/20250303072037_Add&MigrateEventV2.cs
EventHighway.Core/Models/Events/V2/EventV2.cs
EventHighway.Core/Models/Events/V2/EventV2Type.cs
EventHighway.sln

DATA: Add & Migreate Event V2

---

EventHighway.Core/Brokers/Storages/StorageBroker.EventAddressV2s.cs
EventHighway.Core/Brokers/Storages/StorageBroker.EventV2s.Configurations.cs
EventHighway.Core/Brokers/Storages/StorageBroker.EventV2s.cs
EventHighway.Core/Brokers/Storages/StorageBroker.cs
EventHighway.Core/Migrations/20250303072037_Add&MigrateEventV2.Designer.cs
EventHighway.Core/Migrations/20250303072037_Add&MigrateEventV2.cs
EventHighway.Core/Migrations/20250303072705_Add&MigreteEventAddressV2.Designer.cs
EventHighway.Core/Migrations/20250303072705_Add&MigreteEventAddressV2.cs
EventHighway.Core/Migrations/20250303084857_AddEventAddressV2sTable.Designer.cs
EventHighway.Core/Migrations/20250303084857_AddEventAddressV2sTable.cs
EventHighway.Core/Models/EventAddresses/V2/EventAddressV2.cs
EventHighway.Core/Models/Events/V2/EventV2.cs
EventHighway.Core/Models/Events/V2/EventV2Type.cs
EventHighway.sln

DATA: Add & Migrate Event Address V2

---

EventHighway.Core/Brokers/Loggings/ILoggingBroker.cs
EventHighway.Core/Brokers/Loggings/LoggingBroker.cs
EventHighway.Core/Brokers/Storages/IStorageBroker.cs

BROKERS: Log Error

---

EventHighway.Core/Brokers/Storages/IStorageBroker.EventV2s.cs
EventHighway.Core/Brokers/Storages/StorageBroker.EventAddresses.cs
EventHighway.Core/Brokers/Storages/StorageBroker.EventListeners.cs
EventHighway.Core/Brokers/Storages/StorageBroker.EventV2s.cs
EventHighway.Core/Brokers/Storages/StorageBroker.Events.cs

BROKERS: Insert Event V2

---

EventHighway.Core/Brokers/Apis/ApiBroker.cs
EventHighway.Core/Brokers/Storages/IStorageBroker.EventV2s.cs
EventHighway.Core/Brokers/Storages/StorageBroker.EventV2s.cs

BROKERS: Select All Events V2

---

EventHighway.Core/Brokers/Loggings/ILoggingBroker.cs
EventHighway.Core/Brokers/Loggings/LoggingBroker.cs

BROKERS: Log Critical

---

EventHighway.Core.Tests.Unit/Services/Foundations/Events/V2/EventV2ServiceTests.Exceptions.Add.cs
EventHighway.Core.Tests.Unit/Services/Foundations/Events/V2/EventV2ServiceTests.Logic.Add.cs
EventHighway.Core.Tests.Unit/Services/Foundations/Events/V2/EventV2ServiceTests.Validations.Add.cs
EventHighway.Core.Tests.Unit/Services/Foundations/Events/V2/EventV2ServiceTests.cs
EventHighway.Core/Models/Events/V2/Exceptions/AlreadyExistsEventV2Exception.cs
EventHighway.Core/Models/Events/V2/Exceptions/EventV2DependencyException.cs
EventHighway.Core/Models/Events/V2/Exceptions/EventV2DependencyValidationException.cs
EventHighway.Core/Models/Events/V2/Exceptions/EventV2ServiceException.cs
EventHighway.Core/Models/Events/V2/Exceptions/EventV2ValidationException.cs
EventHighway.Core/Models/Events/V2/Exceptions/FailedEventV2ServiceException.cs
EventHighway.Core/Models/Events/V2/Exceptions/FailedEventV2StorageException.cs
EventHighway.Core/Models/Events/V2/Exceptions/InvalidEventV2Exception.cs
EventHighway.Core/Models/Events/V2/Exceptions/InvalidEventV2ReferenceException.cs
EventHighway.Core/Models/Events/V2/Exceptions/NullEventV2Exception.cs
EventHighway.Core/Services/Foundations/Events/V2/EventV2Service.Exceptions.cs
EventHighway.Core/Services/Foundations/Events/V2/EventV2Service.Validations.cs
EventHighway.Core/Services/Foundations/Events/V2/EventV2Service.cs
EventHighway.Core/Services/Foundations/Events/V2/IEventV2Service.cs

FOUNDATIONS: Add Event V2

---

EventHighway.Core.Tests.Unit/Services/Foundations/EventListeners/V2/EventListenerV2ServiceTests.Exceptions.RetrieveAll.cs
EventHighway.Core.Tests.Unit/Services/Foundations/EventListeners/V2/EventListenerV2ServiceTests.Logic.RetrieveAll.cs
EventHighway.Core.Tests.Unit/Services/Foundations/EventListeners/V2/EventListenerV2ServiceTests.cs
EventHighway.Core/Models/EventListeners/V2/Exceptions/EventListenerV2DependencyException.cs
EventHighway.Core/Models/EventListeners/V2/Exceptions/EventListenerV2ServiceException.cs
EventHighway.Core/Models/EventListeners/V2/Exceptions/FailedEventListenerV2ServiceException.cs
EventHighway.Core/Models/EventListeners/V2/Exceptions/FailedEventListenerV2StorageException.cs
EventHighway.Core/Services/Foundations/EventListeners/V2/EventListenerV2Service.Exceptions.cs
EventHighway.Core/Services/Foundations/EventListeners/V2/EventListenerV2Service.cs
EventHighway.Core/Services/Foundations/EventListeners/V2/IEventListenerV2Service.cs

FOUNDATIONS: Retrieve All Event LIsteners V2

---

EventHighway.Core.Tests.Unit/Services/Foundations/Events/V2/EventV2ServiceTests.Exceptions.RetrieveAll.cs
EventHighway.Core.Tests.Unit/Services/Foundations/Events/V2/EventV2ServiceTests.Logic.RetrieveAll.cs
EventHighway.Core.Tests.Unit/Services/Foundations/Events/V2/EventV2ServiceTests.cs
EventHighway.Core/Services/Foundations/Events/V2/EventV2Service.Exceptions.cs
EventHighway.Core/Services/Foundations/Events/V2/EventV2Service.cs
EventHighway.Core/Services/Foundations/Events/V2/IEventV2Service.cs

* Pending #30
* Architecure https://github.com/hassanhabib/EventHighway/pull/15

FOUNDATIONS: Retrieve All Events V2

---

EventHighway.Core/Brokers/Storages/IStorageBroker.ListenerEventV2s.cs
EventHighway.Core/Brokers/Storages/StorageBroker.ListenerEventV2s.cs

BROKERS: Select Listener Event V2 By Id

---

EventHighway.Core.Tests.Unit/Services/Processings/ListenerEvents/V2/ListenerEventV2ProcessingServiceTests.Exceptions.Modify.cs
EventHighway.Core.Tests.Unit/Services/Processings/ListenerEvents/V2/ListenerEventV2ProcessingServiceTests.Logic.Modify.cs
EventHighway.Core.Tests.Unit/Services/Processings/ListenerEvents/V2/ListenerEventV2ProcessingServiceTests.Validations.Modify.cs
EventHighway.Core/Services/Processings/ListenerEvents/V2/IListenerEventV2ProcessingService.cs
EventHighway.Core/Services/Processings/ListenerEvents/V2/ListenerEventV2ProcessingService.cs

PROCESSINGS: Modify Listener Event V2

---

EventHighway.Core.Tests.Unit/Services/Orchestrations/Events/V2/EventV2OrchestrationServiceTests.Exceptions.RetrieveScheduledPending.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/Events/V2/EventV2OrchestrationServiceTests.Logic.RetrieveScheduledPending.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/Events/V2/EventV2OrchestrationServiceTests.cs
EventHighway.Core/Models/Orchestrations/Events/V2/Exceptions/EventV2OrchestrationDependencyException.cs
EventHighway.Core/Models/Orchestrations/Events/V2/Exceptions/EventV2OrchestrationServiceException.cs
EventHighway.Core/Models/Orchestrations/Events/V2/Exceptions/FailedEventV2OrchestrationServiceException.cs
EventHighway.Core/Services/Orchestrations/Events/V2/EventV2OrchestrationService.Exceptions.cs
EventHighway.Core/Services/Orchestrations/Events/V2/EventV2OrchestrationService.cs
EventHighway.Core/Services/Orchestrations/Events/V2/IEventV2OrchestrationService.cs

ORCHESTRATIONS: Retrieve Scheduled Pending Events V2

---

EventHighway.Core.Tests.Unit/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationServiceTests.Exceptions.RetrieveByEventAddressId.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationServiceTests.Logic.RetrieveByEventAddressId.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationServiceTests.Validations.RetrieveByEventAddressId.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationServiceTests.cs
EventHighway.Core/Models/Orchestrations/EventListeners/V2/Exceptions/EventListenerV2OrchestrationDependencyException.cs
EventHighway.Core/Models/Orchestrations/EventListeners/V2/Exceptions/EventListenerV2OrchestrationDependencyValidationException.cs
EventHighway.Core/Models/Orchestrations/EventListeners/V2/Exceptions/EventListenerV2OrchestrationServiceException.cs
EventHighway.Core/Models/Orchestrations/EventListeners/V2/Exceptions/EventListenerV2OrchestrationValidationException.cs
EventHighway.Core/Models/Orchestrations/EventListeners/V2/Exceptions/FailedEventListenerV2OrchestrationServiceException.cs
EventHighway.Core/Models/Orchestrations/EventListeners/V2/Exceptions/InvalidEventListenerV2OrchestrationException.cs
EventHighway.Core/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationService.Exceptions.cs
EventHighway.Core/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationService.Validations.cs
EventHighway.Core/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationService.cs
EventHighway.Core/Services/Orchestrations/EventListeners/V2/IEventListenerV2OrchestrationService.cs

ORCHESTRATIONS: Retrieve Event Listeners V2 By Event Address Id

---

EventHighway.Core.Tests.Unit/Services/Orchestrations/Events/V2/EventV2OrchestrationServiceTests.Exceptions.RetrieveScheduledPending.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/Events/V2/EventV2OrchestrationServiceTests.Exceptions.Run.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/Events/V2/EventV2OrchestrationServiceTests.Logic.RetrieveScheduledPending.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/Events/V2/EventV2OrchestrationServiceTests.Logic.Run.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/Events/V2/EventV2OrchestrationServiceTests.Validations.Run.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/Events/V2/EventV2OrchestrationServiceTests.cs
EventHighway.Core.Tests.Unit/Services/Processings/EventCalls/V2/EventCallV2ProcessingServiceTests.cs
EventHighway.Core/Models/Orchestrations/Events/V2/Exceptions/EventV2OrchestrationDependencyValidationException.cs
EventHighway.Core/Models/Orchestrations/Events/V2/Exceptions/EventV2OrchestrationValidationException.cs
EventHighway.Core/Models/Orchestrations/Events/V2/Exceptions/NullEventCallV2OrchestrationException.cs
EventHighway.Core/Services/Orchestrations/Events/V2/EventV2OrchestrationService.Exceptions.cs
EventHighway.Core/Services/Orchestrations/Events/V2/EventV2OrchestrationService.Validations.cs
EventHighway.Core/Services/Orchestrations/Events/V2/EventV2OrchestrationService.cs
EventHighway.Core/Services/Orchestrations/Events/V2/IEventV2OrchestrationService.cs

ORCHESTRATIONS: Run Event Call V2

---

EventHighway.Core.Tests.Unit/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationServiceTests.Exceptions.AddListenerEventV2.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationServiceTests.Exceptions.RetrieveByEventAddressId.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationServiceTests.Logic.AddListenerEventV2.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationServiceTests.Logic.RetrieveByEventAddressId.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationServiceTests.Validations.AddListenerEventV2.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationServiceTests.Validations.RetrieveByEventAddressId.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationServiceTests.cs
EventHighway.Core/Models/Orchestrations/EventListeners/V2/Exceptions/NullListenerEventV2OrchestrationException.cs
EventHighway.Core/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationService.Exceptions.cs
EventHighway.Core/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationService.Validations.cs
EventHighway.Core/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationService.cs
EventHighway.Core/Services/Orchestrations/EventListeners/V2/IEventListenerV2OrchestrationService.cs

ORCHESTRATIONS: Add Listener Event V2

---

EventHighway.Designs/EVENTS.drawio

DESIGNS: Register & Remove Event Address V2

---

EventHighway.Designs/EVENTS.drawio

DESIGNS: Register & Remove Event Listener V2 

---

EventHighway.Designs/EVENTS.drawio

DESIGNS: Retrieve All & Remove Listener Event V2

---

EventHighway.Core/Brokers/Storages/IStorageBroker.EventAddressV2s.cs

* Architecture: https://github.com/hassanhabib/EventHighway/pull/61

BROKERS: Select Event Address By Id

---

EventHighway.Core/Brokers/Storages/IStorageBroker.EventAddressV2s.cs
EventHighway.Core/Brokers/Storages/StorageBroker.EventAddressV2s.cs

* Pending #62
* Architecture: https://github.com/hassanhabib/EventHighway/pull/58

BROKERS: Insert Event Address V2

---

EventHighway.Core/Brokers/Storages/IStorageBroker.ListenerEventV2s.cs
EventHighway.Core/Brokers/Storages/StorageBroker.ListenerEventV2s.cs

* Architecture: https://github.com/hassanhabib/EventHighway/pull/60

BROKERS: Select All Listener Events V2

---

EventHighway.Core/Brokers/Storages/IStorageBroker.EventAddressV2s.cs
EventHighway.Core/Brokers/Storages/StorageBroker.EventAddressV2s.cs
EventHighway.Core/Brokers/Storages/StorageBroker.cs

* Pending #63
* Architecture: https://github.com/hassanhabib/EventHighway/pull/58

BROKERS: Delete Event Address V2

---

EventHighway.Core/Brokers/Storages/IStorageBroker.EventListenerV2s.cs
EventHighway.Core/Brokers/Storages/StorageBroker.EventListenerV2s.cs

* Pending #64
* Architecture: https://github.com/hassanhabib/EventHighway/pull/59

BROKERS: Delete Event Listener V2 

---

EventHighway.Core/Brokers/Storages/IStorageBroker.ListenerEventV2s.cs
EventHighway.Core/Brokers/Storages/StorageBroker.ListenerEventV2s.cs

* Pending #64 & #67
* Architecture: https://github.com/hassanhabib/EventHighway/pull/60

BROKERS: Delete Listener Event V2

---

EventHighway.Core.Tests.Unit/Services/Foundations/EventAddresses/V2/EventAddressV2ServiceTests.Exceptions.RetrieveById.cs
EventHighway.Core.Tests.Unit/Services/Foundations/EventAddresses/V2/EventAddressV2ServiceTests.Logic.RetrieveById.cs
EventHighway.Core.Tests.Unit/Services/Foundations/EventAddresses/V2/EventAddressV2ServiceTests.Validations.RetrieveById.cs
EventHighway.Core.Tests.Unit/Services/Foundations/EventAddresses/V2/EventAddressV2ServiceTests.cs
EventHighway.Core/Clients/EventHighways/EventHighwayClient.cs
EventHighway.Core/Models/Services/Foundations/EventAddresses/V2/Exceptions/EventAddressV2DependencyException.cs
EventHighway.Core/Models/Services/Foundations/EventAddresses/V2/Exceptions/EventAddressV2DependencyValidationException.cs
EventHighway.Core/Models/Services/Foundations/EventAddresses/V2/Exceptions/EventAddressV2ServiceException.cs
EventHighway.Core/Models/Services/Foundations/EventAddresses/V2/Exceptions/EventAddressV2ValidationException.cs
EventHighway.Core/Models/Services/Foundations/EventAddresses/V2/Exceptions/FailedEventAddressV2ServiceException.cs
EventHighway.Core/Models/Services/Foundations/EventAddresses/V2/Exceptions/FailedEventAddressV2StorageException.cs
EventHighway.Core/Models/Services/Foundations/EventAddresses/V2/Exceptions/InvalidEventAddressV2Exception.cs
EventHighway.Core/Services/Foundations/EventAddresses/V2/EventAddressV2Service.Exceptions.cs
EventHighway.Core/Services/Foundations/EventAddresses/V2/EventAddressV2Service.Validations.cs
EventHighway.Core/Services/Foundations/EventAddresses/V2/EventAddressV2Service.cs
EventHighway.Core/Services/Foundations/EventAddresses/V2/IEventAddressV2Service.cs

* Architecture: https://github.com/hassanhabib/EventHighway/pull/69

FOUNDATIONS: Retrieve Event Address V2 By Id

---

EventHighway.Core.Tests.Unit/Services/Foundations/EventAddresses/V2/EventAddressV2ServiceTests.Exceptions.Add.cs
EventHighway.Core.Tests.Unit/Services/Foundations/EventAddresses/V2/EventAddressV2ServiceTests.Exceptions.RetrieveById.cs
EventHighway.Core.Tests.Unit/Services/Foundations/EventAddresses/V2/EventAddressV2ServiceTests.Logic.Add.cs
EventHighway.Core.Tests.Unit/Services/Foundations/EventAddresses/V2/EventAddressV2ServiceTests.Logic.RetrieveById.cs
EventHighway.Core.Tests.Unit/Services/Foundations/EventAddresses/V2/EventAddressV2ServiceTests.Validations.Add.cs
EventHighway.Core.Tests.Unit/Services/Foundations/EventAddresses/V2/EventAddressV2ServiceTests.Validations.RetrieveById.cs
EventHighway.Core.Tests.Unit/Services/Foundations/EventAddresses/V2/EventAddressV2ServiceTests.cs
EventHighway.Core/Models/Services/Foundations/EventAddresses/V2/Exceptions/AlreadyExistsEventAddressV2Exception.cs
EventHighway.Core/Models/Services/Foundations/EventAddresses/V2/Exceptions/NullEventAddressV2Exception.cs
EventHighway.Core/Services/Foundations/EventAddresses/V2/EventAddressV2Service.Exceptions.cs
EventHighway.Core/Services/Foundations/EventAddresses/V2/EventAddressV2Service.Validations.cs
EventHighway.Core/Services/Foundations/EventAddresses/V2/EventAddressV2Service.cs
EventHighway.Core/Services/Foundations/EventAddresses/V2/IEventAddressV2Service.cs

* Pending #73
* Architecture: https://github.com/hassanhabib/EventHighway/pull/70

FOUNDATIONS: Add Event Address V2 

---

EventHighway.Core.Tests.Unit/Services/Foundations/EventAddresses/V2/EventAddressV2ServiceTests.Exceptions.RemoveById.cs
EventHighway.Core.Tests.Unit/Services/Foundations/EventAddresses/V2/EventAddressV2ServiceTests.Logic.RemoveById.cs
EventHighway.Core.Tests.Unit/Services/Foundations/EventAddresses/V2/EventAddressV2ServiceTests.Validations.RemoveById.cs
EventHighway.Core/Models/Services/Foundations/EventAddresses/V2/Exceptions/LockedEventAddressV2Exception.cs
EventHighway.Core/Models/Services/Foundations/EventAddresses/V2/Exceptions/NotFoundEventAddressV2Exception.cs
EventHighway.Core/Services/Foundations/EventAddresses/V2/EventAddressV2Service.Exceptions.cs
EventHighway.Core/Services/Foundations/EventAddresses/V2/EventAddressV2Service.Validations.cs
EventHighway.Core/Services/Foundations/EventAddresses/V2/EventAddressV2Service.cs
EventHighway.Core/Services/Foundations/EventAddresses/V2/IEventAddressV2Service.cs

* Pending #74
* Architecture: https://github.com/hassanhabib/EventHighway/pull/70

FOUNDATIONS: Remove Event Address V2 By Id

---

EventHighway.Designs/EVENTS.drawio

STATUS: Register & Remove Event Address V2 As Of 13-03-25 

---

EventHighway.Designs/EVENTS.drawio

STATUS: Register & Remove Event Listener V2 As Of 13-03-25 

---

EventHighway.Designs/EVENTS.drawio

STATUS: Retrieve All & Remove Listener Event V2 As Of 13-03-25 

---

EventHighway.Core.Tests.Unit/Services/Processings/ListenerEvents/V2/ListenerEventV2ProcessingServiceTests.Exceptions.RetrieveAll.cs
EventHighway.Core.Tests.Unit/Services/Processings/ListenerEvents/V2/ListenerEventV2ProcessingServiceTests.Logic.RetrieveAll.cs
EventHighway.Core.Tests.Unit/Services/Processings/ListenerEvents/V2/ListenerEventV2ProcessingServiceTests.cs
EventHighway.Core/Services/Foundations/ListernEvents/V2/IListenerEventV2Service.cs
EventHighway.Core/Services/Processings/ListenerEvents/V2/IListenerEventV2ProcessingService.cs
EventHighway.Core/Services/Processings/ListenerEvents/V2/ListenerEventV2ProcessingService.Exceptions.cs
EventHighway.Core/Services/Processings/ListenerEvents/V2/ListenerEventV2ProcessingService.cs

* Architecture: https://github.com/hassanhabib/EventHighway/pull/83

PROCESSINGS: Retrieve All Listener Events V2 

---

EventHighway.Core.Tests.Unit/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationServiceTests.Exceptions.RetrieveAllListenerEventV2s.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationServiceTests.Logic.RetrieveAllListenerEventV2s.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationServiceTests.cs
EventHighway.Core/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationService.Exceptions.cs
EventHighway.Core/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationService.cs
EventHighway.Core/Services/Orchestrations/EventListeners/V2/IEventListenerV2OrchestrationService.cs

* Architecture: https://github.com/hassanhabib/EventHighway/pull/83

ORCHESTRATIONS: Retrieve All Listener Events V2

---

EventHighway.Core.Tests.Unit/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationServiceTests.Exceptions.RemoveListenerEventV2ById.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationServiceTests.Logic.RemoveListenerEventV2ById.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationServiceTests.Validations.RemoveListenerEventV2ById.cs
EventHighway.Core/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationService.Exceptions.cs
EventHighway.Core/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationService.Validations.cs
EventHighway.Core/Services/Orchestrations/EventListeners/V2/EventListenerV2OrchestrationService.cs
EventHighway.Core/Services/Orchestrations/EventListeners/V2/IEventListenerV2OrchestrationService.cs

* Architecture: https://github.com/hassanhabib/EventHighway/pull/83
* Pending #88

ORCHESTRATIONS: Remove Listener Events V2 By Id 

---

EventHighway.Designs/EVENTS.drawio

STATUS: Register & Remove Event Listener V2 As Of 17-03-25

---

EventHighway.Designs/EVENTS.drawio

STATUS: Submit & Remove Event V2 As Of 18-03-25 

---

EventHighway.Core.Tests.Unit/Services/Processings/Events/V2/EventV2ProcessingServiceTests.Exceptions.Add.cs
EventHighway.Core.Tests.Unit/Services/Processings/Events/V2/EventV2ProcessingServiceTests.Logic.Add.cs
EventHighway.Core.Tests.Unit/Services/Processings/Events/V2/EventV2ProcessingServiceTests.Validations.Add.cs
EventHighway.Core/Models/Services/Processings/Events/V2/Exceptions/NullEventV2ProcessingException.cs
EventHighway.Core/Services/Processings/Events/V2/EventV2ProcessingService.Exceptions.cs
EventHighway.Core/Services/Processings/Events/V2/EventV2ProcessingService.Validations.cs
EventHighway.Core/Services/Processings/Events/V2/EventV2ProcessingService.cs
EventHighway.Core/Services/Processings/Events/V2/IEventV2ProcessingService.cs

* Achitecture: https://github.com/hassanhabib/EventHighway/pull/101

PROCESSINGS: Add Event V2

---

EventHighway.Core.Tests.Unit/Services/Processings/EventAddresses/V2/EventAddressV2ProcessingServiceTests.Exceptions.RetrieveById.cs
EventHighway.Core.Tests.Unit/Services/Processings/EventAddresses/V2/EventAddressV2ProcessingServiceTests.Logic.RetrieveById.cs
EventHighway.Core.Tests.Unit/Services/Processings/EventAddresses/V2/EventAddressV2ProcessingServiceTests.Validations.RetrieveById.cs
EventHighway.Core.Tests.Unit/Services/Processings/EventAddresses/V2/EventAddressV2ProcessingServiceTests.cs
EventHighway.Core.Tests.Unit/Services/Processings/Events/V2/EventV2ProcessingServiceTests.Exceptions.RemoveById.cs
EventHighway.Core/Models/Services/Processings/EventAddresses/V2/Exceptions/EventAddressV2ProcessingDependencyException.cs
EventHighway.Core/Models/Services/Processings/EventAddresses/V2/Exceptions/EventAddressV2ProcessingDependencyValidationException.cs
EventHighway.Core/Models/Services/Processings/EventAddresses/V2/Exceptions/EventAddressV2ProcessingServiceException.cs
EventHighway.Core/Models/Services/Processings/EventAddresses/V2/Exceptions/EventAddressV2ProcessingValidationException.cs
EventHighway.Core/Models/Services/Processings/EventAddresses/V2/Exceptions/FailedEventAddressV2ProcessingServiceException.cs
EventHighway.Core/Models/Services/Processings/EventAddresses/V2/Exceptions/InvalidEventAddressV2ProcessingException.cs
EventHighway.Core/Services/Processings/EventAddresses/V2/EventAddressV2ProcessingService.Exceptions.cs
EventHighway.Core/Services/Processings/EventAddresses/V2/EventAddressV2ProcessingService.Validations.cs
EventHighway.Core/Services/Processings/EventAddresses/V2/EventAddressV2ProcessingService.cs
EventHighway.Core/Services/Processings/EventAddresses/V2/IEventAddressV2ProcessingService.cs

* Achitecture: https://github.com/hassanhabib/EventHighway/pull/101

PROCESSINGS: Retrieve Event Address V2 By Id

---

EventHighway.Designs/EVENTS.drawio

STATUS: Submit & Remove Event V2 As Of 19-03-25

---

EventHighway.Core.Tests.Unit/Services/Orchestrations/Events/V2/EventV2OrchestrationServiceTests.Exceptions.RetrieveScheduledPending.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/Events/V2/EventV2OrchestrationServiceTests.Exceptions.Run.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/Events/V2/EventV2OrchestrationServiceTests.Exceptions.Submit.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/Events/V2/EventV2OrchestrationServiceTests.Logic.RetrieveScheduledPending.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/Events/V2/EventV2OrchestrationServiceTests.Logic.Run.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/Events/V2/EventV2OrchestrationServiceTests.Logic.Submit.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/Events/V2/EventV2OrchestrationServiceTests.Validations.Run.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/Events/V2/EventV2OrchestrationServiceTests.Validations.Submit.cs
EventHighway.Core.Tests.Unit/Services/Orchestrations/Events/V2/EventV2OrchestrationServiceTests.cs
EventHighway.Core.Tests.Unit/Services/Processings/Events/V2/EventV2ProcessingServiceTests.Exceptions.Add.cs
EventHighway.Core/Models/Services/Orchestrations/Events/V2/Exceptions/NotFoundEventAddressV2OrchestrationException.cs
EventHighway.Core/Models/Services/Orchestrations/Events/V2/Exceptions/NullEventV2OrchestrationException.cs
EventHighway.Core/Services/Orchestrations/Events/V2/EventV2OrchestrationService.Exceptions.cs
EventHighway.Core/Services/Orchestrations/Events/V2/EventV2OrchestrationService.Validations.cs
EventHighway.Core/Services/Orchestrations/Events/V2/EventV2OrchestrationService.cs
EventHighway.Core/Services/Orchestrations/Events/V2/IEventV2OrchestrationService.cs

* Pending #102 & #103
* Achitecture: https://github.com/hassanhabib/EventHighway/pull/101

ORCHESTRATIONS: Submit Event V2

---

EventHighway.Core.Tests.Unit/Services/Coordinations/V2/EventV2CoordinationServiceTests.Exceptions.Submit.cs
EventHighway.Core.Tests.Unit/Services/Coordinations/V2/EventV2CoordinationServiceTests.Logic.Submit.cs
EventHighway.Core.Tests.Unit/Services/Coordinations/V2/EventV2CoordinationServiceTests.Validations.Submit.cs
EventHighway.Core.Tests.Unit/Services/Coordinations/V2/EventV2CoordinationServiceTests.cs
EventHighway.Core/Models/Services/Coordinations/Events/V2/Exceptions/NullEventV2CoordinationException.cs
EventHighway.Core/Services/Coordinations/Events/V2/EventV2CoordinationService.Exceptions.cs
EventHighway.Core/Services/Coordinations/Events/V2/EventV2CoordinationService.Validations.cs
EventHighway.Core/Services/Coordinations/Events/V2/EventV2CoordinationService.cs
EventHighway.Core/Services/Coordinations/Events/V2/IEventV2CoordinationService.cs

* Pending #104
* Achitecture: https://github.com/hassanhabib/EventHighway/pull/101

COORDINATIONS: Submit Event V2 

---

EventHighway.Designs/EVENTS.drawio

STATUS: Register & Remove Event Address V2 As Of 20-03-25 

---

EventHighway.Designs/EVENTS.drawio

STATUS: Register & Remove Event Listener V2 As Of 20-03-25 

---

EventHighway.Core.Tests.Unit/Clients/Events/V2/EventV2sClientTests.Exceptions.RemoveById.cs
EventHighway.Core.Tests.Unit/Clients/Events/V2/EventV2sClientTests.Exceptions.Submit.cs
EventHighway.Core.Tests.Unit/Clients/Events/V2/EventV2sClientTests.Logic.RemoveById.cs
EventHighway.Core.Tests.Unit/Clients/Events/V2/EventV2sClientTests.cs
EventHighway.Core/Clients/Events/V2/EventV2sClient.cs
EventHighway.Core/Clients/Events/V2/IEventV2sClient.cs

CLIENTS: Remove Event V2 By Id

---

EventHighway.Core.Tests.Unit/Clients/EventListeners/V2/EventListenerV2sClientTests.Exceptions.RemoveById.cs
EventHighway.Core.Tests.Unit/Clients/EventListeners/V2/EventListenerV2sClientTests.Logic.RemoveById.cs
EventHighway.Core.Tests.Unit/Clients/EventListeners/V2/EventListenerV2sClientTests.Validations.RemoveById.cs
EventHighway.Core.Tests.Unit/Clients/EventListeners/V2/EventListenerV2sClientTests.cs
EventHighway.Core/Clients/EventListeners/V2/EventListenerV2sClient.cs
EventHighway.Core/Clients/EventListeners/V2/IEventListenerV2sClient.cs

CLIENTS: Remove Event Listener V2 By Id 

---

EventHighway.Core/Clients/EventHighways/EventHighwayClient.cs
EventHighway.Core/Clients/EventHighways/IEventHighwayClient.cs

CONFIGS: Register Dependencies

---

EventHighway.Core.Tests.Unit/Clients/ListenerEvents/V2/ListenerEventV2sClientTests.Exceptions.RemoveById.cs
EventHighway.Core.Tests.Unit/Clients/ListenerEvents/V2/ListenerEventV2sClientTests.Logic.RemoveById.cs
EventHighway.Core.Tests.Unit/Clients/ListenerEvents/V2/ListenerEventV2sClientTests.cs
EventHighway.Core/Clients/ListenerEvents/V2/IListenerEventV2sClient.cs
EventHighway.Core/Clients/ListenerEvents/V2/ListenerEventV2sClient.cs

CLIENTS: Remove Listener Event V2 By Id

---

EventHighway.Core.Tests.Unit/Services/Foundations/EventAddresses/V1/EventAddressV1ServiceTests.Exceptions.RetrieveAll.cs
EventHighway.Core.Tests.Unit/Services/Foundations/EventAddresses/V1/EventAddressV1ServiceTests.Logic.RetrieveAll.cs
EventHighway.Core.Tests.Unit/Services/Foundations/EventAddresses/V1/EventAddressV1ServiceTests.cs
EventHighway.Core/Services/Foundations/EventAddresses/V1/EventAddressV1Service.Exceptions.cs
EventHighway.Core/Services/Foundations/EventAddresses/V1/EventAddressV1Service.cs
EventHighway.Core/Services/Foundations/EventAddresses/V1/IEventAddressV1Service.cs

FOUNDATIONS: Retrieve All Event Addresses V1

---

EventHighway.Core.Tests.Acceptance/Brokers/ClientBroker.EventAddressV1s.cs
EventHighway.Core.Tests.Unit/Clients/EventAddresses/V1/EventAddressesV1ClientTests.Exceptions.Register.cs
EventHighway.Core.Tests.Unit/Clients/EventAddresses/V1/EventAddressesV1ClientTests.Exceptions.RemoveById.cs
EventHighway.Core.Tests.Unit/Clients/EventAddresses/V1/EventAddressesV1ClientTests.Exceptions.RetrieveAll.cs
EventHighway.Core.Tests.Unit/Clients/EventAddresses/V1/EventAddressesV1ClientTests.Logic.Register.cs
EventHighway.Core.Tests.Unit/Clients/EventAddresses/V1/EventAddressesV1ClientTests.Logic.RemoveById.cs
EventHighway.Core.Tests.Unit/Clients/EventAddresses/V1/EventAddressesV1ClientTests.Logic.RetrieveAll.cs
EventHighway.Core.Tests.Unit/Clients/EventAddresses/V1/EventAddressesV1ClientTests.cs
EventHighway.Core.Tests.Unit/Clients/ListenerEvents/V1/ListenerEventV1sClientTests.Exceptions.RemoveById.cs
EventHighway.Core.Tests.Unit/Clients/ListenerEvents/V1/ListenerEventV1sClientTests.Exceptions.RetrieveAll.cs
EventHighway.Core.Tests.Unit/Clients/ListenerEvents/V1/ListenerEventV1sClientTests.Logic.RemoveById.cs
EventHighway.Core.Tests.Unit/Clients/ListenerEvents/V1/ListenerEventV1sClientTests.Logic.RetrieveAll.cs
EventHighway.Core.Tests.Unit/Clients/ListenerEvents/V1/ListenerEventV1sClientTests.cs
EventHighway.Core/Clients/EventAddresses/V1/EventAddressesV1Client.cs
EventHighway.Core/Clients/EventAddresses/V1/IEventAddressesV1Client.cs
EventHighway.Core/Clients/EventHighways/EventHighwayClient.cs
EventHighway.Core/Clients/EventHighways/IEventHighwayClient.cs

CLIENTS: Retrieve All Event Addresses V1 

---

EventHighway.Core.Tests.Unit/Services/Foundations/Events/V1/EventV1ServiceTests.Logic.Modify.cs
EventHighway.Core.Tests.Unit/Services/Foundations/Events/V1/EventV1ServiceTests.Validations.Modify.cs
EventHighway.Core/Services/Foundations/Events/V1/EventV1Service.Validations.cs
EventHighway.Core/Services/Foundations/Events/V1/EventV1Service.cs
EventHighway.Core/Services/Foundations/Events/V1/IEventV1Service.cs

* Pending #152 
* Closes https://github.com/hassanhabib/EventHighway/issues/156

FOUNDATIONS: Modify Event V1

---

.github/workflows/dotnet.yml
EventHighway.App/EventHighway.App.csproj
EventHighway.Core.Tests.Acceptance/EventHighway.Core.Tests.Acceptance.csproj
EventHighway.Core.Tests.Unit/EventHighway.Core.Tests.Unit.csproj
EventHighway.Core/EventHighway.Core.csproj

* This PR  is ready
* Closes: #162

CONFIG: Upgrade Project to .Net 9
